Changed models but not finished
WeDish/wedish_backend pull request #27
Opened 2022-04-20 17:47 UTC by midrox

Kiek supratau pakeiciau

2022-04-20 18:07 UTC, infohata requested changes

2022-04-20 18:07 UTC, infohata commented on wedish/wedish_accounting/models.py
>      price = models.CharField(_('Price'), max_length=100, db_index=True)
Price turi buti DecimalField (paziurekit kituose apps'uose pvz. jau yra)

2022-04-20 18:07 UTC, infohata commented on wedish/wedish_accounting/models.py
> +    place = models.ForeignKey(
import Place

2022-04-20 18:07 UTC, infohata commented on wedish/wedish_accounting/models.py
> +
order fk to Order

2022-04-20 18:07 UTC, infohata commented on wedish/wedish_accounting/models.py
> +        on_delete=models.CASCADE,
PROTECT

2022-04-21 15:46 UTC, infohata commented
reikia `pub` app kad sumergint

2022-04-21 17:17 UTC, infohata requested changes

2022-04-21 17:17 UTC, infohata commented on wedish/wedish_accounting/models.py
> +    # country = country fk i partraukti salis (Countries) is django_cities_light #11 tasko importuota Country
jau galima padaryti, main branch'e yra cities_light

2022-04-22 11:57 UTC, midrox commented on wedish/wedish_accounting/models.py
> +    # country = country fk i partraukti salis (Countries) is django_cities_light #11 tasko importuota Country
bandziau daryt fk i cities_light bet nelabai suprantu kaip tai padaryt.

2022-04-25 15:14 UTC, infohata commented on wedish/wedish_accounting/admin.py
> +class OrderLineAdmin(admin.ModelAdmin):
sutvarkyti

2022-04-25 15:40 UTC, merged